# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86a103e8563b48f07ea9be1ac371b2c738e74764d0495f49bbd02eb686a7c7d4fca0a256b1dbd88dfe92623dc58aa7b920a9a81f2953ccabc959539cd37e54b0

test:
  secret_key_base: a0d4996c1a714ca8dfc1c5e0955c27ce74142a12aa478d79089738cc41df342a9621cfc75ac752cae20f5e5b8c5cad277044c3712144cf045ab29eff8b7fcf63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
